import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  /* config options here */
  publicRuntimeConfig: {
    firebaseApiKey: process.env.DEALSBURST_PUBLIC_FIREBASE_API_KEY,
    firebaseAuthDomain: process.env.DEALSBURST_PUBLIC_FIREBASE_AUTH_DOMAIN,
  },
  serverRuntimeConfig: {
    DEALSBURST_PRIVATE_FIREBASE_PROJECT_ID: process.env.DEALSBURST_PRIVATE_FIREBASE_PROJECT_ID,
    DEALSBURST_PRIVATE_FIREBASE_STORAGE_BUCKET: process.env.DEALSBURST_PRIVATE_FIREBASE_STORAGE_BUCKET,
    DEALSBURST_PRIVATE_FIREBASE_CLIENT_EMAIL: process.env.DEALSBURST_PRIVATE_FIREBASE_CLIENT_EMAIL,
    DEALSBURST_PRIVATE_FIREBASE_PRIVATE_KEY: process.env.DEALSBURST_PRIVATE_FIREBASE_PRIVATE_KEY,
    DEALSBURST_PUBLIC_FIREBASE_MESSAGING_SENDER_ID: process.env.DEALSBURST_PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
    DEALSBURST_PUBLIC_FIREBASE_APP_ID: process.env.DEALSBURST_PUBLIC_FIREBASE_APP_ID,
    DEALSBURST_PUBLIC_FIREBASE_MEASUREMENT_ID: process.env.DEALSBURST_PUBLIC_FIREBASE_MEASUREMENT_ID
  }
};

export default nextConfig;
